/** Export final report as Markdown (issue #11) */
export interface ReportSection { title: string; lines: string[]; }
export interface FinalReport { summary: string; sections: ReportSection[]; }
export function exportReportAsMarkdown(report: FinalReport): string {
  const lines: string[] = [`# Gomi Agent Report`, '', `> ${report.summary}`, ''];
  for (const section of report.sections) {
    lines.push(`## ${section.title}`, '');
    for (const line of section.lines) lines.push(`- ${line}`);
    lines.push('');
  }
  lines.push(`---`, `*Generated by Gomi IDE*`);
  return lines.join('\n');
}
